services:
  fe:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: fe
    volumes:
      - ./fe:/opt/app
      - ./scripts:/opt/scripts:ro
    ports:
      - 5173:5173
  tools:
    build:
      context: .
      dockerfile: Dockerfile
      target: tools
    volumes:
      - .:/opt/app
