name: CI

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  code_format:
    # Set up operating system
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Define job steps
    steps:
      - name: Check-out repository
        uses: actions/checkout@v7

      - name: Setup python
        uses: astral-sh/setup-uv@v8.3.0
        with:
          ignore-nothing-to-cache: 'true'

      - name: Install dependencies
        run: docker compose run --rm tools npm install

      - name: Install pre-commit and run
        run: uvx pre-commit run --all-files

  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check-out repository
        uses: actions/checkout@v7

      - name: Install dependencies
        run: docker compose run --rm fe npm install

      - name: Build
        run: docker compose run --rm fe npm run build

      - name: Run e2e tests
        run: docker compose run --rm fe npm run test:e2e
