name: code_format

on:
  workflow_call:

jobs:
  format:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Build containers
      run: docker compose build

    - name: Install dependencies
      run: docker compose run --rm fe npm install

    - name: Format with prettier
      run: docker compose run --rm fe npx prettier . --write

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install pre-commit and run
      run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files || pre-commit run --all-files

    - name: Commit any changes
      uses: stefanzweifel/git-auto-commit-action@v5
      id: auto-commit-action
      with:
        commit_message: Apply prettier/pre-commit changes
        branch: code-formatting
        create_branch: true

    - name: "Create PR if changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Code changes!"
        gh pr create --title "Code formatting" --body "Changes from code formatting" --base main --head code-formatting

    - name: Merge PR and delete branch
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pr_number=$(gh pr list --state open --limit 1 --json number --jq '.[0].number')
        gh pr merge $pr_number --merge --delete-branch

    - name: "Run if no changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: echo "No code changes!"
